# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2e3ac1d31b3b5fb897d05f8b0d2bf510136411f6f1c7647b08cfcb3bc6fa14d7b444fb47677b11863ab93875cb2666fdfd3b15d2c62174a35766bc6a761c5072

test:
  secret_key_base: 686f4bc81a9c10a5ad350177a34ab66d2576eb503c71085e75694cb672e597f6e875fc8fea56ede1b3594d8f15841b2bc8b25bb3c28f97572354322d194e097d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
